"""Added collum to named account pw resets table.

Revision ID: 0241a490f122
Revises: 33562295114a
Create Date: 2017-11-21 08:53:36.772896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0241a490f122'
down_revision = '33562295114a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('named_account_password_resets', sa.Column('type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('named_account_password_resets', 'type')
    # ### end Alembic commands ###
