"""Added name based accounts

Revision ID: bd07d88725d9
Revises: 10a08adb17d5
Create Date: 2017-11-07 07:11:36.728900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd07d88725d9'
down_revision = '10a08adb17d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('named_account_password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('acct', sa.String(length=100), nullable=True),
    sa.Column('acct_location', sa.String(length=100), nullable=True),
    sa.Column('reset_date', sa.Date(), nullable=True),
    sa.Column('reset_day', sa.String(length=100), nullable=True),
    sa.Column('reset_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_account_password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('acct', sa.String(length=100), nullable=True),
    sa.Column('acct_location', sa.String(length=100), nullable=True),
    sa.Column('reset_date', sa.Date(), nullable=True),
    sa.Column('reset_day', sa.String(length=100), nullable=True),
    sa.Column('reset_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('warehouse_password_resets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_password_resets',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('agent', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('acct', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('acct_location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('reset_date', sa.DATE(), nullable=True),
    sa.Column('reset_day', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('reset_type', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('role_account_password_resets')
    op.drop_table('named_account_password_resets')
    # ### end Alembic commands ###
